CREATE TABLE topicos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(70) NOT NULL,
  mensaje LONGTEXT NOT NULL,
  fecha_creacion DATE NOT NULL,
  estatus VARCHAR(50) NOT NULL,
  autor BIGINT NOT NULL,
  curso BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE);